import Head from 'next/head'
import styles from '../styles/Home.module.css'
import WelcomeScreen from '../components/WelcomeScreen'
import { useMetamask } from '../hooks/useMetamask'
import { DEPLOYED_CHAIN_ID } from '../constants/chain_config'

export default function Home() {

  const { chainID } = useMetamask();

  return (
    <div className={styles.container}>
      <Head>
        <title>Blockchain Pharmacy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pharmacyFavicon.png" />
      </Head>

      {/* Will need conditional rendering within this block, to render <Prescriber/> and <Patient/> and <Admin/> based on smart contract read */}
      {(chainID == DEPLOYED_CHAIN_ID) &&
        <WelcomeScreen/>
      }
    </div>
  )
}
